# /*
#  * @Author: 胖胖很瘦
#  * @Date: 2025-03-17 13:04:47
#  * @LastEditors: 胖胖很瘦
#  * @LastEditTime: 2025-03-18 16:19:39
#  */
# 微信风格技术博客主题配置

# 导航菜单
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# 社交链接
social:
  github: https://github.com/Mehaei
  # twitter: https://twitter.com/yourname
  # weibo: https://weibo.com/yourname
  # zhihu: https://www.zhihu.com/people/yourname
  email: pymehaei@gmail.com

# 网站图标
favicon: /images/default-icon.png

# 头像
avatar: /images/avatar.jpg

# 首页设置
index:
  post_list_style: card # card or simple
  show_excerpt: true
  excerpt_length: 150
  show_read_more: true
  show_thumbnail: true
  default_thumbnail: /images/default-post-thumbnail.png
  show_stats: true

# 文章页设置
post:
  show_date: true
  show_categories: true
  show_tags: true
  show_toc: true
  show_updated: true
  show_prev_next: true
  show_share: true
  show_stats: true
  show_author_profile: false

# 广告位配置
advertisement:
  enable: false
  header_ad: false
  sidebar_ad: true
  content_ad: true
  footer_ad: false

# 统计与分析
analytics:
  enable: true
  baidu_analytics: 
  google_analytics: 
  cnzz_analytics:

# 评论系统 (Gitalk基于GitHub Issues)
comments:
  enable: true
  type: gitalk # gitalk, disqus, valine等
  gitalk:
    clientID: Ov23lio49dK17kuXohqu
    clientSecret: d17123fb396f8a474c450f46ad0aa5dc17d004db
    repo: mehaei.github.io
    owner: Mehaei
    admin: ['Mehaei']
    distractionFreeMode: false


# 微信公众号
wechat_mp:
  enable: true
  qrcode: /images/wechat-qrcode.jpg
  description: '扫码关注「不止于python」公众号'

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '  '
  wrap: true
  hljs: false

# 加载动画
loading_progress: true

# 左下角看板娘配置
waifu: true

# 暗黑模式
dark_mode: false

# 侧边栏设置
sidebar:
  enable: true
  position: right  # 可以是 left 或 right
  sticky: true     # 是否固定侧边栏
  show_on_post: true  # 在文章页面显示侧边栏
  author:
    enable: true
    avatar: /images/avatar.jpg
    bio: '人均全栈开发'
  search:
    enable: true
  categories:
    enable: true
    sort: name # name 或 count
    limit: 10 # 显示的分类数量，0表示显示全部
  tags:
    enable: true
    limit: 30 # 显示的标签数量，0表示显示全部
    min_font: 12 # 最小字体大小
    max_font: 24 # 最大字体大小
  hot_posts:
    enable: true
    limit: 5 # 显示的文章数量
    sort: views # date, views, or comments
  archives:
    enable: true
    limit: 8 # 显示的归档数量
  monthly_chart:
    enable: true
  links:
    enable: true
    items:
      Hexo官网: https://hexo.io
      GitHub: https://github.com
      Stack Overflow: https://stackoverflow.com

# 打赏功能
reward:
  enable: true
  wechat: /images/wechat-reward.png
  alipay: /images/alipay-reward.png

# 搜索功能配置
search:
  enable: true
  max_results: 50  # 最大搜索结果条数

# 网站统计配置
statistics:
  enable: true
  # 网站运行时间起始日期
  runtime:
    enable: true
    date: 2023/1/1    # 修改为您的网站开始运行日期
  # 访问统计
  visitor:
    enable: true
    # 是否显示总访问量(PV)
    show_pv: true
    # 是否显示总访客数(UV)
    show_uv: true

# 关于页面配置
about:
  title: "关于我"
  description: "记录自己在程序员职业生涯中遇到的各种问题，学习到的新知识，以及奇闻趣事。"
  # experience: "多年python爬虫,全栈,后端经验"
  # hobbies: "喜欢编程、阅读、旅行和摄影。喜欢折腾，热衷于新技术，特别是 AI 技术，积极将其应用于实际项目中。"
  projects: ""
  # projects:
  #   - name: "项目A"
  #     description: "描述项目A的内容和技术栈。"
  #   - name: "项目B"
  #     description: "描述项目B的内容和技术栈。"
  #   - name: "项目C"
  #     description: "描述项目C的内容和技术栈。"
  # goals: "我希望在未来能够成为一名全栈开发工程师。"
  goals: ""
  skills: 
    - "Python"
    - "JavaScript"
    - "HTML/CSS"
    - "后端主流框架 (Tornado/FastAPI/Django/Flask/Sanic)"
    - "SQL/NoSQL (MySQL/PostgreSQL/Kingbase/MongoDB/Redis)"
    - "爬虫与数据采集 (Scrapy/requests/aiohttp)"
    - "自动化测试 (Selenium/Pyppeteer/Appium)"
    - "Docker"
    - "Git/SVN"
    - "RabbitMQ"
    - "Nginx"
    - "Linux/Shell"
    - "数据可视化 (Matplotlib/Echarts/Numpy/Pandas)"
    - "AI 技术"
    - "天文学基础"